### ISSUE TITLE
Broken version file

### ISSUE THREAD

**Issue by Olympic1** [Rjoande/RealBattery#2]
With the update for 1.3 you accidently added an space to `KSP_VERSION_MIN` in the version file, which makes it an invalid format.

https://github.com/blackliner/RealBattery/blob/master/RealBattery/GameData/RealBattery/RealBattery.version#L17

Removing the space before the `"` will fix this issue.

**Comment by blackliner** [comment]
Holy crap, totally lost you issue. Thanks for participating, I fixed that 2 days ago, CKAN should be updated now as well.
